/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from 'ethers'
import { Listener, Provider } from 'ethers/providers'
import { Arrayish, BigNumber, BigNumberish, Interface } from 'ethers/utils'
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription,
} from '.'

interface ArbSysInterface extends Interface {
  functions: {
    addressTable_lookupAddress: TypedFunctionDescription<{
      encode([add, should_register]: [string, boolean]): string
    }>

    addressTable_lookupIndex: TypedFunctionDescription<{
      encode([index]: [BigNumberish]): string
    }>

    getStorageAt: TypedFunctionDescription<{
      encode([account, index]: [string, BigNumberish]): string
    }>

    getTransactionCount: TypedFunctionDescription<{
      encode([account]: [string]): string
    }>

    withdrawERC20: TypedFunctionDescription<{
      encode([dest, amount]: [string, BigNumberish]): string
    }>

    withdrawERC721: TypedFunctionDescription<{
      encode([dest, id]: [string, BigNumberish]): string
    }>

    withdrawEth: TypedFunctionDescription<{ encode([dest]: [string]): string }>
  }

  events: {}
}

export class ArbSys extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ArbSys
  attach(addressOrName: string): ArbSys
  deployed(): Promise<ArbSys>

  on(event: EventFilter | string, listener: Listener): ArbSys
  once(event: EventFilter | string, listener: Listener): ArbSys
  addListener(eventName: EventFilter | string, listener: Listener): ArbSys
  removeAllListeners(eventName: EventFilter | string): ArbSys
  removeListener(eventName: any, listener: Listener): ArbSys

  interface: ArbSysInterface

  functions: {
    addressTable_lookupAddress(
      add: string,
      should_register: boolean,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    'addressTable_lookupAddress(address,bool)'(
      add: string,
      should_register: boolean,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    addressTable_lookupIndex(
      index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>

    'addressTable_lookupIndex(uint256)'(
      index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>

    getStorageAt(
      account: string,
      index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    'getStorageAt(address,uint256)'(
      account: string,
      index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    getTransactionCount(
      account: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    'getTransactionCount(address)'(
      account: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    withdrawERC20(
      dest: string,
      amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>

    'withdrawERC20(address,uint256)'(
      dest: string,
      amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>

    withdrawERC721(
      dest: string,
      id: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>

    'withdrawERC721(address,uint256)'(
      dest: string,
      id: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>

    withdrawEth(
      dest: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>

    'withdrawEth(address)'(
      dest: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>
  }

  addressTable_lookupAddress(
    add: string,
    should_register: boolean,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>

  'addressTable_lookupAddress(address,bool)'(
    add: string,
    should_register: boolean,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>

  addressTable_lookupIndex(
    index: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>

  'addressTable_lookupIndex(uint256)'(
    index: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>

  getStorageAt(
    account: string,
    index: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>

  'getStorageAt(address,uint256)'(
    account: string,
    index: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>

  getTransactionCount(
    account: string,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>

  'getTransactionCount(address)'(
    account: string,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>

  withdrawERC20(
    dest: string,
    amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>

  'withdrawERC20(address,uint256)'(
    dest: string,
    amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>

  withdrawERC721(
    dest: string,
    id: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>

  'withdrawERC721(address,uint256)'(
    dest: string,
    id: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>

  withdrawEth(
    dest: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>

  'withdrawEth(address)'(
    dest: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>

  filters: {}

  estimate: {
    addressTable_lookupAddress(
      add: string,
      should_register: boolean,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    'addressTable_lookupAddress(address,bool)'(
      add: string,
      should_register: boolean,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    addressTable_lookupIndex(
      index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    'addressTable_lookupIndex(uint256)'(
      index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    getStorageAt(
      account: string,
      index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    'getStorageAt(address,uint256)'(
      account: string,
      index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    getTransactionCount(
      account: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    'getTransactionCount(address)'(
      account: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    withdrawERC20(
      dest: string,
      amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    'withdrawERC20(address,uint256)'(
      dest: string,
      amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    withdrawERC721(
      dest: string,
      id: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    'withdrawERC721(address,uint256)'(
      dest: string,
      id: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    withdrawEth(
      dest: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>

    'withdrawEth(address)'(
      dest: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>
  }
}
